# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish Javadocs

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nelonoel/branch-name@v1.0.1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install GH import
      run: |
        python -m pip install --upgrade pip
        pip install ghp-import

    - name: Checkout NeuroML2
      uses: actions/checkout@v2
      with:
        repository: NeuroML/NeuroML2
        ref: development
        path: NeuroML2

    - name: Checkout org.neuroml.model.injectingplugin
      uses: actions/checkout@v2
      with:
        repository: NeuroML/org.neuroml.model.injectingplugin
        ref: development
        path: org.neuroml.model.injectingplugin

    - name: Install NeuroML deps
      run: |
        pushd NeuroML2
        mvn install
        popd
        pushd org.neuroml.model.injectingplugin
        mvn install
        popd

    - name: Build docs
      run: |
        mvn javadoc:javadoc

    - name: Publish documentation on GH pages
      run: |
        ghp-import -f -m "Regenerate documentation" -b gh-pages -n -p target/site/apidocs

